export const END_POINTS = {
  LOGIN: 'api/Auth/Login',
  GET_HERO_SECTION: 'api/admin/HeroSection',
  UPDATE_HERO_SECTION: 'api/admin/HeroSection',
  DASHBOARD_STATISTICS: 'api/admin/Dashboard',
  LIST_PROJECTS: 'api/admin/Project/Search/',
  ADD_PROJECT: 'api/admin/Project',
  ADD_MEDIA: 'api/admin/Media',
  GET_PROJECT: 'api/admin/Project/',
  UPDATE_PROJECT: 'api/admin/Project',
  DELETE_PROJECT: 'api/admin/Project',
  GET_ABOUT_US: 'api/admin/AboutUs',
  GET_PRIVACY_POLICY: 'api/admin/PrivacyPolicy',
  GET_CONSTRUCTIONS: 'api/admin/Constructions',
  GET_DEVELOPMENT: 'api/admin/Developments',
  GET_AD_SECTION: 'api/admin/AdSection',
  GET_GUARANTEE_SECTION: 'api/admin/GuaranteeSection',
};
